# Generated by Django 6.0.1 on 2026-01-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='days',
            field=models.JSONField(default=list),
        ),
    ]
